name: syncfusion_flutter_datepicker
description: The Flutter Date Range Picker widget allows users to easily select dates or a range of dates. It has four built-in views that allow quick navigation to the desired date.
version: 20.2.40
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_datepicker

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: 0.17.0
  syncfusion_flutter_core: 20.4.54

dev_dependencies:
  flutter_test:
    sdk: flutter